# @package _global_

# specify here default training configuration
defaults:
  - trainer: default_trainer.yaml
  - model: model.yaml
  - optimizer: adam.yaml
  - datamodule: datamodule.yaml
  - callbacks: default_callbacks.yaml  # set this to null if you don't want to use callbacks
  - logger: wandb.yaml  # set logger here or use command line (e.g. `python train.py logger=wandb`)

  # enable color logging
  # - override hydra/hydra_logging: colorlog
  # - override hydra/job_logging: colorlog


# path to original working directory (that `train.py` was executed from in command line)
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have path to original work dir as a special variable
# read more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory

testing: true
weights: "/home/yuchunli/git/kaggle-shopee/f1=0.745.ckpt"

# path to folder with data
data_dir: "/home/yuchunli/_DATASET/shopee-product-matching"

# use `python train.py debug=true` for easy debugging!
# this will run 1 train, val and test loop with only 1 batch
# equivalent to running `python train.py trainer.fast_dev_run=true`
# (this is placed here just for easier access from command line)
debug: False


# pretty print config at the start of the run using Rich library
print_config: True


# disable python warnings if they annoy you
disable_warnings: True